apiVersion: example.upbound.io/v1alpha1
kind: Website
metadata:
  name: website
  namespace: demo-website
spec:
  deletionPolicy: Delete
  parameters:
    bucket:
      name: platform-ref-s3-website
      path: /static
      forceDestroy: true
    defaultRootObject: index.html
    description: platform-ref-s3-website
    domain:
      name: demo.website.myhostcloud.de
      zoneId: Z033029419NV7XCJOKZ9I
    enabled: true
    region: eu-central-1
    tags:
      CostReference: PSP-12345
  providerConfigRef:
    name: default
