apiVersion: example.upbound.io/v1alpha1
kind: DNSZone
metadata:
  name: demo
  namespace: demo-website
spec:
  deletionPolicy: Orphan
  parameters:
    domain:
      zoneName: website.example.cloud
    region: us-east-1
    tags:
      CostReference: PSP-12345
  providerConfigRef:
    name: default
