apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdnszones.example.upbound.io
spec:
  claimNames:
    kind: DNSZone
    plural: dnszones
  group: example.upbound.io
  names:
    categories:
    - websites
    - composition
    - crossplane
    kind: XDNSZone
    plural: xdnszones
  versions:
  - name: v1alpha1
    additionalPrinterColumns:
    - description: The zoneId from route53 Zone
      jsonPath: .status.hostedzone.zoneId
      name: zoneId
      type: string
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: dns zone configuration parameters.
                properties:
                  region:
                    type: string
                    description: Region is the region youre bucket is located.
                  domain:
                    description: domain configuration field
                    properties:
                      zoneName:
                        description: Name of the hosted zone.
                        type: string
                    type: object
                  tags:
                    description: Map of additional AWS Tags to add to resources
                    additionalProperties:
                      type: string
                    type: object
              deletionPolicy:
                type: string
                description: DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource.
              providerConfigRef:
                type: object
                description: crossplane provider credentials to use.
                properties:
                  name:
                    type: string
                required:
                - name
            required:
            - parameters
            - deletionPolicy
            - providerConfigRef
          status:
            properties:
              hostedzone:
                description: Useful values generated from the S3 API.
                type: object
                x-kubernetes-preserve-unknown-fields: true
                type: object
            type: object
